config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'homes#index'
  resource :users
  resources :shares, only: %i[new create index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/timeline.rb
class Timeline < ApplicationRecord
  belongs_to :prev_user, class_name: 'User', foreign_key: :prev_user_id
  belongs_to :child_user, class_name: 'User', foreign_key: :child_user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :timelines
  after_create :create_referral_code, :check_points

  def create_referral_code
    code = email.split('@').first
    value = id * 2
    code = "#{value}_#{code}_#{rand(value)}"
    update(joining_referral_code: code)
  end

  def check_points
    prev_user = previous_user
    return if prev_user.nil?

    time_lines = Timeline.where(prev_user:)
    if time_lines.length >= 1
      update_points(prev_user, 10)
      update_points(self, 5)
      update_points(time_lines.last.child_user, 5)
      time_lines.destroy_all
    else
      Timeline.create!(prev_user:, child_user: self)
    end
  end

  def update_points(user, value)
    ReferralMailer.refer_through_email(user).deliver_now
    points = user.points
    points += value
    user.update(points:)
  end

  def previous_user
    User.find_by(joining_referral_code: referral_code)
  end
  # User.create!("referral_code"=>"user01", "name"=>"user04", "email"=>"user01@example.com", "password"=>"welcome", "password_confirmation"=>"welcome")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, :referral_code])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def new; end

  def index; end

  def create
    if params[:email]
      ReferralMailer.refer_through_email(current_user, new_user_registration_url, params[:email]).deliver_now
      flash[notice:] = 'Mail sended'
    else
      flash[alert:] = 'Went Wrong'
    end
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    p @code = params[:code]
    p @email = params[:email]
    super
  end

  # POST /resource
  def create
    if @code.present?
      pre_user = User.find_by(joining_referral_code: @code)
      if pre_user.nil?
        flash[:error] = 'Invalid referral code, Please try again'
        redirect_to(new_user_registration_path) and return
      end
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def user_params
    params.require(:user).permit(:name, :email, :referral_code, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/share_helper.rb
module ShareHelper
end

app/views/homes/_refere_page.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Popup Title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>
        <%= form_with( url: shares_path, method: "post") do |f| %>
          <div class="field">
            <%= f.label :Referral_code %>:</tr>
            <%= f.label current_user.joining_referral_code %><br />
          </div>
            <br/>
          <div class="field">
            <%= f.label :Name %>:</tr>
            <%= f.label current_user.name %><br />
          </div>
          <div class="field">
            <%= f.label :Refer_through_email %>:
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Others email" %> <%= f.submit "Share joining link" %>
          </div>
        <% end %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

<% if user_signed_in? %>
 <%= button_to "Sign out", destroy_user_session_path, method: :delete %> </tr>
<p>Name: <%= current_user.name %></p>
<p>Email: <%= current_user.email %></p>
<p>Points: <%= current_user.points %></p>
<p>Referral Code: <%= current_user.joining_referral_code %></p>
<%= link_to 'Refer', shares_path, class: 'btn btn-primary', data: { toggle: 'modal' } %>
<div class="open-pop-up"></div>
<% else %>
  <%= button_to "Sign up", new_user_registration_path %> 
  <%= button_to "Sign in", new_user_session_path %> 
<p>  </p>

<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReferralApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/shares/_refere_page.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%# <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Popup Title</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> %>
      <div class="modal-body">
        <p>
        <%= form_with(url: shares_path, method: "post") do |f| %>
        
          <div class="field">
            <%= f.label :Refer_to_friend %>:
            <%= f.email_field :email, autofocus: true, placeholder: "Others email" %> <%= f.submit "Share joining link" %>
          </div>
        <% end %>
        </p>
      </div>
      <div class="modal-footer">
      <%= link_to 'Back to Home', root_path %>
        <%# <button type="button" class="btn btn-default" data-dismiss="modal">Home</button> %>
      </div>
    </div>
  </div>
</div>

app/views/shares/index.html.erb
<p>Hi thus is me</p>
 <%= render partial: 'shares/refere_page' %> 